---
- name: create service account
  command: oc --context {{ cluster.context }} create serviceaccount {{ service_account_name }} -n {{ namespace }}
  register: oc_res
  failed_when: oc_res.rc >= 2
  
- name: add permissions to the service account
  command: oc --context {{ cluster.context }} adm policy add-cluster-role-to-user cluster-reader -z {{ service_account_name }} -n {{ namespace }}
  
- name: get the service account secret name
  shell: oc --context {{ cluster.context }} describe serviceaccount {{ service_account_name }} -n {{ namespace }} | grep Tokens | awk '{print $2}'
  register: secret_name
  
- name: get the service account token 
  shell: oc --context {{ cluster.context }} describe secret {{ secret_name.stdout }} -n {{ namespace }} | grep "token:" | awk '{print $2}'
  register: token

- name: Add token to Clusters
  set_fact:
    tmp_cluster: "{{ [ (clusters | selectattr('name', 'match', cluster.name) | list | combine([{'token': token.stdout }]))] }}"       
  
- name: Update Clusters
  set_fact:
    clusters: "{{ clusters | rejectattr('name', 'match', cluster['name']) | list }} + {{ tmp_cluster }}"    