---
- name: get coredns account secret name
  shell: oc --context {{ cluster.context }} get secret -n {{ namespace }} | grep -m 1 coredns-token | awk '{print $1}'
  register: secret_name

- name: get ca_data
  command: oc --context {{ cluster.context }} get secret {{ secret_name.stdout }} -n {{ namespace }} -o "jsonpath={.data['ca\.crt']}"
  register: ca_data
  
- name: get token
  shell: oc --context {{ cluster.context }} get secret {{ secret_name.stdout }} -n {{ namespace }} -o "jsonpath={.data['token']}" | base64 --decode
  register: token

- name: Add ca and token to Clusters
  set_fact:
    tmp_cluster: "{{ [ (clusters | selectattr('name', 'match', cluster.name) | list | combine({'ca_data': ca_data.stdout, 'coredns_sa_token': token.stdout })) ] }}"

- name: Update Clusters
  set_fact:
    clusters: "{{ clusters | rejectattr('name', 'match', cluster.name) | list }} + {{ tmp_cluster }}"     
