---
- name: process service account template
  template:
    src: coredns-service-account.yaml.j2
    dest: "/tmp/{{ cluster.name }}-coredns-service-account.yaml"
    
- name: apply service account template
  command: oc --context {{ cluster.context }} apply -f /tmp/{{ cluster.name }}-coredns-service-account.yaml    