---
- name: add ips to cluster
  include_tasks: add-ips.yaml
  with_items: "{{ clusters }}"
  loop_control:
    loop_var: cluster
  when: tunnel_mode != 'wireguard4'  

- name: debug
  debug:
    var: clusters