---
- hosts: localhost
  connection: local
  roles:
  - role: initialize-data
  - role: create-services
  - role: prepare-keys
  - role: retrieve-public-ips 
  - role: create-ds
  - role: retrieve-pods-ips
  - role: create-cm  


    