# oc get nodes -o custom-columns=NAME:metadata.name --no-headers=true

---
# oc get nodes -o custom-columns=NAME:metadata.name --no-headers=true
- name: login to the clusters
  include_tasks: authenticate.yaml
  with_items: "{{ clusters }}"
  loop_control:
    loop_var: cluster

- name: add the node name to the dictionary
  include_tasks: add-nodes.yaml
  with_items: "{{ clusters }}"
  loop_control:
    loop_var: cluster
    
- name: add the node cidr to the dictionary
  include_tasks: add-cluster-cidr.yaml
  with_items: "{{ clusters }}"
  loop_control:
    loop_var: cluster
    
- name: debug
  debug:
    var: clusters
    
- name: create cluster services
  include_tasks: create-services.yaml
  with_items: "{{ clusters }}"
  loop_control:
    loop_var: cluster
    
- name: add keys to cluster
  include_tasks: add-keys.yaml
  with_items: "{{ clusters }}"
  loop_control:
    loop_var: cluster
    
- name: debug
  debug:
    var: clusters 
    
- name: add public ips to cluster
  include_tasks: add-ips.yaml
  with_items: "{{ clusters }}"
  loop_control:
    loop_var: cluster
  when: tunnel_mode != 'wireguard4'  

- name: debug
  debug:
    var: clusters

- name: create cluster daemonsets
  include_tasks: create-ds.yaml
  with_items: "{{ clusters }}"
  loop_control:
    loop_var: cluster                
          
         